#!/bin/bash

echo "Cleaning directory and Cargo cache..."

rm -rf ~/.cargo/registry/cache > /dev/null
rm -rf ./src > /dev/null
rm -rf ./target > /dev/null
rm Cargo.lock > /dev/null
rm Cargo.toml > /dev/null

echo "Initializing Cargo project with rustc-std-workspace-core package..."
cargo init > /dev/null
echo "rustc-std-workspace-core = \"^1.0.0\"" >> ./Cargo.toml

echo "Running clean Cargo build..."
cargo build > /dev/null

echo "Done!"