# fly.toml app configuration file generated for omnitory on 2023-11-07T13:53:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "omnitory"
primary_region = "ams"

[env]
# ARWEAVE_KEY = ****
# HCAPTCHA_SECRET = ****
  ARWEAVE_GATEWAY_URL= "https://node2.irys.xyz/"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
